### ISSUE TITLE
ibmcloud panics with recent build with error panic: detect: not detected

### ISSUE THREAD

**Issue by mkumatag** [IBM-Cloud/ibm-cloud-cli-release#187]
Installed via:

```shell
# curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
Current platform is linux64. Downloading corresponding IBM Cloud CLI...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.8M  100 11.8M    0     0   623k      0  0:00:19  0:00:19 --:--:--  615k
Download complete. Executing installer...
Bluemix_CLI/
Bluemix_CLI/bin/
Bluemix_CLI/bin/ibmcloud
Bluemix_CLI/bin/ibmcloud.sig
Bluemix_CLI/bin/NOTICE
Bluemix_CLI/bin/LICENSE
Bluemix_CLI/bin/CF_CLI_Notices.txt
Bluemix_CLI/bin/CF_CLI_SLC_Notices.txt
Bluemix_CLI/autocomplete/
Bluemix_CLI/autocomplete/bash_autocomplete
Bluemix_CLI/autocomplete/zsh_autocomplete
Bluemix_CLI/install
Bluemix_CLI/uninstall
Bluemix_CLI/install_bluemix_cli
Install complete.
```

```shell
# ibmcloud --help
panic: detect: not detected

goroutine 1 [running]:
github.ibm.com/SoftLayer/softlayer-cli/plugin/i18n.DetectLocal()
	/home/travis/gopath/pkg/mod/github.ibm.com/!soft!layer/softlayer-cli@v1.0.8/plugin/i18n/i18n.go:72 +0x105
github.ibm.com/SoftLayer/softlayer-cli/plugin/i18n.supportedLocale({0x0?, 0x0?})
	/home/travis/gopath/pkg/mod/github.ibm.com/!soft!layer/softlayer-cli@v1.0.8/plugin/i18n/i18n.go:90 +0x54
github.ibm.com/SoftLayer/softlayer-cli/plugin/i18n.Init({0x7f969fe1d028?, 0xc00002b5c0?})
	/home/travis/gopath/pkg/mod/github.ibm.com/!soft!layer/softlayer-cli@v1.0.8/plugin/i18n/i18n.go:45 +0x2f
github.ibm.com/SoftLayer/softlayer-cli/plugin/i18n.init()
	/home/travis/gopath/pkg/mod/github.ibm.com/!soft!layer/softlayer-cli@v1.0.8/plugin/i18n/i18n.go:41 +0xd2
root@ac72f13a87fb:/workspace# ibmcloud version
panic: detect: not detected

goroutine 1 [running]:
github.ibm.com/SoftLayer/softlayer-cli/plugin/i18n.DetectLocal()
	/home/travis/gopath/pkg/mod/github.ibm.com/!soft!layer/softlayer-cli@v1.0.8/plugin/i18n/i18n.go:72 +0x105
github.ibm.com/SoftLayer/softlayer-cli/plugin/i18n.supportedLocale({0x0?, 0x0?})
	/home/travis/gopath/pkg/mod/github.ibm.com/!soft!layer/softlayer-cli@v1.0.8/plugin/i18n/i18n.go:90 +0x54
github.ibm.com/SoftLayer/softlayer-cli/plugin/i18n.Init({0x7f069cb5ca98?, 0xc00001d680?})
	/home/travis/gopath/pkg/mod/github.ibm.com/!soft!layer/softlayer-cli@v1.0.8/plugin/i18n/i18n.go:45 +0x2f
github.ibm.com/SoftLayer/softlayer-cli/plugin/i18n.init()
	/home/travis/gopath/pkg/mod/github.ibm.com/!soft!layer/softlayer-cli@v1.0.8/plugin/i18n/i18n.go:41 +0xd2
root@ac72f13a87fb:/workspace# LANG=en_US.UTF-8
root@ac72f13a87fb:/workspace# ibmcloud version
panic: detect: not detected

goroutine 1 [running]:
github.ibm.com/SoftLayer/softlayer-cli/plugin/i18n.DetectLocal()
	/home/travis/gopath/pkg/mod/github.ibm.com/!soft!layer/softlayer-cli@v1.0.8/plugin/i18n/i18n.go:72 +0x105
github.ibm.com/SoftLayer/softlayer-cli/plugin/i18n.supportedLocale({0x0?, 0x0?})
	/home/travis/gopath/pkg/mod/github.ibm.com/!soft!layer/softlayer-cli@v1.0.8/plugin/i18n/i18n.go:90 +0x54
github.ibm.com/SoftLayer/softlayer-cli/plugin/i18n.Init({0x7f16a19b1028?, 0xc000340240?})
	/home/travis/gopath/pkg/mod/github.ibm.com/!soft!layer/softlayer-cli@v1.0.8/plugin/i18n/i18n.go:45 +0x2f
github.ibm.com/SoftLayer/softlayer-cli/plugin/i18n.init()
	/home/travis/gopath/pkg/mod/github.ibm.com/!soft!layer/softlayer-cli@v1.0.8/plugin/i18n/i18n.go:41 +0xd2
root@ac72f13a87fb:/workspace#
```

There is already workaround mentioned in the release not and it works fine, e.g:
```shell
# export LANG=en_US.UTF-8
root@ac72f13a87fb:/workspace# ibmcloud version
ibmcloud version 2.11.0+6fd5c4e-2022-09-22T18:49:33+00:00
root@ac72f13a87fb:/workspace#
```

But it should not panic, instead show some meaningful message and ask user check that particular variable.

**Comment by steveclay** [comment]
This is now fixed in release 2.11.1.
