### ISSUE TITLE
Update to 0.10.0 doesn't work on a French locale Mac OS X after upgrading from 0.9.0

### ISSUE THREAD

**Issue by othomann** [IBM-Cloud/ibm-cloud-cli-release#58]
I had 0.9.0 bx cli tool installed. I got prompted for an update so I did and after the update bx no longer runs. I am getting:
```
mbp-de-olivier:pipeline-docker-base-image olivier$ bx
panic: invalid character 'ï' looking for beginning of value

goroutine 1 [running]:
github.ibm.com/Bluemix/bluemix-cli/vendor/github.ibm.com/Bluemix/ibm-softlayer-cli/plugin/i18n.initWithLocale(0x1c6797e, 0x5, 0x1c6797e)
    /Users/appops/go/src/github.ibm.com/Bluemix/bluemix-cli/vendor/github.ibm.com/Bluemix/ibm-softlayer-cli/plugin/i18n/i18n.go:61 +0xa3
github.ibm.com/Bluemix/bluemix-cli/vendor/github.ibm.com/Bluemix/ibm-softlayer-cli/plugin/i18n.Init(0x2dc4150, 0xc420010890, 0x232fca0, 0x24d85a8, 0xc420010890)
    /Users/appops/go/src/github.ibm.com/Bluemix/bluemix-cli/vendor/github.ibm.com/Bluemix/ibm-softlayer-cli/plugin/i18n/i18n.go:55 +0xa5
github.ibm.com/Bluemix/bluemix-cli/vendor/github.ibm.com/Bluemix/ibm-softlayer-cli/plugin/i18n.init()
    /Users/appops/go/src/github.ibm.com/Bluemix/bluemix-cli/vendor/github.ibm.com/Bluemix/ibm-softlayer-cli/plugin/i18n/i18n.go:41 +0x17e
github.ibm.com/Bluemix/bluemix-cli/vendor/github.ibm.com/Bluemix/ibm-softlayer-cli/plugin/errors.init()
    <autogenerated>:1 +0x49
github.ibm.com/Bluemix/bluemix-cli/vendor/github.ibm.com/Bluemix/ibm-softlayer-cli/plugin/client.init()
    <autogenerated>:1 +0x91
github.ibm.com/Bluemix/bluemix-cli/vendor/github.ibm.com/Bluemix/ibm-softlayer-cli/plugin.init()
    <autogenerated>:1 +0x7d
main.init()
    <autogenerated>:1 +0x49
```

I had to revert to 0.9.0 to be able to use bx again.

**Comment by othomann** [comment]
Note that the update message asked for O/N and I need to put Y to get the upgrade.

**Comment by sideralis** [comment]
Same issue with Ubuntu 18.04 and also in French.

**Comment by boyang9527** [comment]
@othomann  @sideralis 
This has been fixed in v0.10.1 which was released today.  Go to release page below to download and install

https://github.com/IBM-Cloud/ibm-cloud-cli-release/releases/tag/v0.10.1

**Comment by sideralis** [comment]
Thanks, it is working now.

**Comment by othomann** [comment]
Thanks, validated locally.
